"""Add TeamRecommendation model

Revision ID: dce556a35c89
Revises: a1f2e3d4c5b6
Create Date: 2026-08-19 16:01:54.353716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dce556a35c89'
down_revision: Union[str, None] = 'a1f2e3d4c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_recommendation_id'), 'team_recommendation', ['id'], unique=False)
    op.create_index(op.f('ix_team_recommendation_user_id'), 'team_recommendation', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'MEMBER', name='teammemberrole'), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_members_team_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='team_members_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='team_members_pkey'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_user')
    )
    op.create_index('ix_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('ix_team_members_id', 'team_members', ['id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='invitationstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='team_invitations_receiver_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='team_invitations_sender_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_invitations_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='team_invitations_pkey')
    )
    op.create_index('ix_team_invitations_team_id', 'team_invitations', ['team_id'], unique=False)
    op.create_index('ix_team_invitations_sender_id', 'team_invitations', ['sender_id'], unique=False)
    op.create_index('ix_team_invitations_receiver_id', 'team_invitations', ['receiver_id'], unique=False)
    op.create_index('ix_team_invitations_id', 'team_invitations', ['id'], unique=False)
    op.create_table('team_recommendations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='team_recommendations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='team_recommendations_pkey')
    )
    op.create_index('ix_team_recommendations_user_id', 'team_recommendations', ['user_id'], unique=True)
    op.create_index('ix_team_recommendations_id', 'team_recommendations', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('max_members', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'FULL', 'LOCKED', name='teamstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('domains', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='teams_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_teams_owner_id', 'teams', ['owner_id'], unique=False)
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    op.create_table('team_join_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='joinrequeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_join_requests_team_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='team_join_requests_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='team_join_requests_pkey')
    )
    op.create_index('ix_team_join_requests_user_id', 'team_join_requests', ['user_id'], unique=False)
    op.create_index('ix_team_join_requests_team_id', 'team_join_requests', ['team_id'], unique=False)
    op.create_index('ix_team_join_requests_id', 'team_join_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_team_recommendation_user_id'), table_name='team_recommendation')
    op.drop_index(op.f('ix_team_recommendation_id'), table_name='team_recommendation')
    op.drop_table('team_recommendation')
    # ### end Alembic commands ###
